<?php

namespace HealthCareAbroad\MedicalProcedureBundle\Repository;

use HealthCareAbroad\MedicalProcedureBundle\Entity\MedicalProcedureType;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalProcedureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalProcedureTypeRepository extends EntityRepository
{
	public function search($term = '', $limit = 10)
	{
		$dql = "
			SELECT c
			FROM MedicalProcedureBundle:MedicalProcedureType AS c
			WHERE c.name LIKE :term
			ORDER BY c.name ASC"
		;
	
		$query = $this->_em->createQuery($dql);
		$query->setParameter('term', "%$term%");
		$query->setMaxResults($limit);
	
		return $query->getResult();
	}
	
	/**
	 * Get QueryBuilder for getting active medical procedure types that can be used for dropdown field types
	 * 
	 * @return Doctrine\ORM\QueryBuilder
	 */
	public function getQueryBuilderForGettingAvailableMedicalProcedureTypes()
	{
	    return $this->getEntityManager()->createQueryBuilder()
            ->add('select', 't')
            ->add('from', 'MedicalProcedureBundle:MedicalProcedureType t')
            ->add('where', 't.status = :active')
	        ->setParameter('active', MedicalProcedureType::STATUS_ACTIVE);
	}
}