<?php

namespace HealthCareAbroad\MedicalProcedureBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalProcedureRepository extends EntityRepository
{
	public function search($term = '', $limit = 10)
	{
		$dql = "
			SELECT p
			FROM MedicalProcedureBundle:MedicalProcedure AS p
			WHERE p.name LIKE :term
			ORDER BY p.name ASC"
		;
	
		$query = $this->_em->createQuery($dql);
		$query->setParameter('term', "%$term%");
		$query->setMaxResults($limit);
	
		return $query->getResult();
	}
	
	
}