<?php

namespace HealthCareAbroad\MedicalProcedureBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalTermSuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalTermSuggestionRepository extends EntityRepository
{
}