<?php

namespace HealthCareAbroad\MedicalProcedureBundle\Repository;

use Doctrine\ORM\QueryBuilder;

use Doctrine\ORM\Query\Expr\Join;

use HealthCareAbroad\MedicalProcedureBundle\Entity\MedicalProcedure;

use HealthCareAbroad\InstitutionBundle\Entity\InstitutionMedicalProcedureType;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalProcedureRepository extends EntityRepository
{
	public function search($term = '', $limit = 10)
	{
		$dql = "
			SELECT p
			FROM MedicalProcedureBundle:MedicalProcedure AS p
			WHERE p.name LIKE :term
			ORDER BY p.name ASC"
		;
	
		$query = $this->_em->createQuery($dql);
		$query->setParameter('term', "%$term%");
		$query->setMaxResults($limit);
	
		return $query->getResult();
	}
	
	public function getCountByMedicalProcedureTypeId($medicalProcedureTypeId) {
		$qb = $this->getEntityManager()->createQueryBuilder();
		$qb->select('count(a)')
	        ->from('MedicalProcedureBundle:MedicalProcedure', 'a')
	        ->where('a.status = :active')
	        ->andWhere('a.medicalProcedureType = :medicalPRocedureTypeId')
			->setParameter('active', MedicalProcedure::STATUS_ACTIVE)
			->setParameter('medicalPRocedureTypeId', $medicalProcedureTypeId);
		
		$count = (int)$qb->getQuery()->getSingleScalarResult();
		
		return $count;
	}
	
	/**
	 * Get query builder for getting available MedicalProcedures that can be used by InstitutionMedicalProcedureType 
	 * 
	 * @param InstitutionMedicalProcedureType $institutionMedicalProcedureType
	 */
	public function getQueryBuilderForAvailableInstitutionMedicalProcedures(InstitutionMedicalProcedureType $institutionMedicalProcedureType)
	{
	    /**
	     SELECT a . * , b . *
        FROM `medical_procedures` a
        LEFT JOIN `institution_medical_procedures` b ON a.id = b.medical_procedure_id
        AND b.institution_medical_procedure_type_id =2
        WHERE a.medical_procedure_type_id =7
        AND b.id IS NULL
	     **/
	    
	    // create query builder similar to above raw sql
	    $qb = $this->getEntityManager()->createQueryBuilder();
	    $qb->select('a')
	        ->from('MedicalProcedureBundle:MedicalProcedure', 'a')
	        ->leftJoin('a.institutionMedicalProcedures', 'b', Join::WITH, 'b.institutionMedicalProcedureType = :institutionMedicalProcedureTypeId')
	        ->where('a.status = :active')
	        ->andWhere('a.medicalProcedureType = :medicalProcedureTypeId')
	        ->andWhere('b.id IS NULL')
	        ->setParameter('active', MedicalProcedure::STATUS_ACTIVE)
	        ->setParameter('medicalProcedureTypeId', $institutionMedicalProcedureType->getMedicalProcedureType()->getId())
	        ->setParameter('institutionMedicalProcedureTypeId', $institutionMedicalProcedureType->getId());
	    return $qb;
	}
	
}