<?php

namespace HealthCareAbroad\MedicalProcedureBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalCenterRepository extends EntityRepository
{
	function searchMedicalCenters($term = '', $limit = 10)
	{
		$query = $this->_em->createQuery("SELECT MedicalCenter.id, MedicalCenter.name FROM MedicalProcedureBundle:MedicalCenter AS MedicalCenter WHERE MedicalCenter.name LIKE '%$term%' AND MedicalCenter.status = 1 ORDER BY MedicalCenter.name ASC");
		$result = $query->setMaxResults($limit)->getArrayResult();
		$data = array();
	
		foreach($result as $centers) {
			$data[] = array(
					'id' => $centers['id'],
					'value' => $centers['name']
			);
		}

		return $data;
	}
}