<?php

namespace HealthCareAbroad\ProviderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{
	static function getProviders() {
		return $this->_em->createQueryBuilder('p')->where('p.status = 1')->orderBy('p.name', 'ASC');
	}
}