<?php

namespace HealthCareAbroad\ProviderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderInvitationRepository extends EntityRepository
{
}