<?php

namespace HealthCareAbroad\ProviderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderUserRepository extends EntityRepository
{
}