<?php

namespace HealthCareAbroad\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{    
    public function getMediaByIds($mediaIds = array())
    {
        $qb = $this->createQueryBuilder('a');
        $qb->add('where', $qb->expr()->in('a.id', $mediaIds));

        return $qb->getQuery()->getResult();
    }
}