<?php

namespace HealthCareAbroad\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function findWithInstitution($mediaId, $institutionId)
    {
        $dql = 'SELECT m FROM MediaBundle:Media m 
                LEFT JOIN m.gallery g 
                LEFT JOIN g.institution i
                WHERE m.id = :mediaId AND i.id = :institutionId';

        $query = $this->_em->createQuery($dql);
        $query->setParameter('mediaId', $mediaId);
        $query->setParameter('institutionId', $institutionId);
        
        return $query->getOneOrNullResult();    	
    }
}