<?php

namespace HealthCareAbroad\TermBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TermDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermDocumentRepository extends EntityRepository
{
}