<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

use HealthCareAbroad\InstitutionBundle\Entity\Doctor;

use Doctrine\ORM\EntityRepository;

/**
 * DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorRepository extends EntityRepository
{
    /**
     * Get all doctors that are active
     */
    public function getActiveDoctors()
    {
        $dql = "SELECT a FROM InstitutionBundle:Doctor a WHERE a.status = :active";
        $query = $this->getEntityManager()->createQuery($dql)    
                      ->setParameter('active', Doctor::STATUS_ACTIVE);
        
        return $query->getResult();
    }
    
    public function getDoctorsBySearchTerm($searchTerm, $institutionId)
    {
        
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('a')
                ->from('InstitutionBundle:Doctor', 'a')
                ->leftJoin('a.institutionDoctors', 'b', Join::WITH, 'b.institution = :institution')
                ->where('a.status = :active')
                ->andWhere('b.id IS NULL')
                ->andWhere('a.firstName LIKE :searchTerm OR a.middleName LIKE :searchTerm OR a.lastName LIKE :searchTerm')
                ->setParameter('searchTerm', '%'.$searchTerm.'%')
                ->setParameter('institution', $institutionId)
                ->setParameter('active', Doctor::STATUS_ACTIVE)
                ->getQuery();

        return $query->getResult();
    }
    
}