<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use Doctrine\Common\Collections\Criteria;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionUserPasswordTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionUserPasswordTokenRepository extends EntityRepository
{
    public function findToken($token, $includeExpired = false)
    {
        if ($includeExpired) {
            return $this->findOneByToken($token);
        }

        $query = $this->_em->createQuery('SELECT t FROM InstitutionBundle:InstitutionUserPasswordToken t WHERE t.token = :token AND t.expirationDate > CURRENT_DATE()');
        $query->setParameter('token', $token);

        return $query->getOneOrNullResult();
    }
}