<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use HealthCareAbroad\InstitutionBundle\Entity\InstitutionTreatment;

use HealthCareAbroad\InstitutionBundle\Entity\InstitutionMedicalCenter;

use Doctrine\ORM\EntityRepository;



/**
 * InstitutionTreatmentProcedureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionTreatmentRepository extends EntityRepository
{
	public function getCountByTreatmentId($medicalProcedureTypeId) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('count(a)')
			->from('InstitutionBundle:InstitutionTreatmentProcedureType', 'a')
			->where('a.status = :active')
			->andWhere('a.medicalProcedureType = :medicalProcedureTypeId')
			->setParameter('active', InstitutionTreatment::STATUS_ACTIVE)
			->setParameter('medicalProcedureTypeId', $medicalProcedureTypeId);
	
		$count = (int)$qb->getQuery()->getSingleScalarResult();
		return $count;
	}
}