<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionUserPasswordTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionUserPasswordTokenRepository extends EntityRepository
{
    
}