<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use HealthCareAbroad\InstitutionBundle\Entity\InstitutionProperty;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionPropertyRepository extends EntityRepository
{
    /**
     * Get all anicilliary services
     */
    public function getAllServicesByInstitution($institution)
    {
        $connection = $this->getEntityManager()->getConnection();
        $query = "SELECT * FROM institution_properties a LEFT JOIN offered_services b ON b.id = a.value WHERE a.institution_id = :id";
        $stmt = $connection->prepare($query);
        $stmt->bindValue('id', $institution->getId());
        $stmt->execute();
        
        return $stmt->fetchAll();
        
    }
}