<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use HealthCareAbroad\InstitutionBundle\Entity\InstitutionTreatment;

use HealthCareAbroad\InstitutionBundle\Entity\InstitutionMedicalCenter;

use Doctrine\ORM\EntityRepository;



/**
 * InstitutionTreatmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionTreatmentRepository extends EntityRepository
{
	public function getCountByTreatmentId($treatmentId) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('count(a)')
			->from('InstitutionBundle:InstitutionTreatment', 'a')
			->where('a.status = :active')
			->andWhere('a.treatment = :treatmentId')
			->setParameter('active', InstitutionTreatment::STATUS_ACTIVE)
			->setParameter('treatmentId', $treatmentId);
	
		$count = (int)$qb->getQuery()->getSingleScalarResult();
		return $count;
	}
}