<?php

namespace HealthCareAbroad\InstitutionBundle\Repository;

use HealthCareAbroad\InstitutionBundle\Entity\Doctor;
use HealthCareAbroad\InstitutionBundle\Entity\InstitutionDoctor;
use HealthCareAbroad\InstitutionBundle\Entity\Institution;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;

/**
 * InstitutionDoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionDoctorRepository extends EntityRepository
{
    function getDoctorsList($institutionId) {
    
        $qb = $this->_em->createQueryBuilder()
        ->select('b.id, b.firstName, b.middleName, b.lastName')
        ->from('InstitutionBundle:InstitutionDoctor', 'a')
        ->leftJoin('a.doctor', 'b')
        ->add('where','a.institution = :institutionId')
        ->setParameter('institutionId', $institutionId);
        return $qb->getQuery()->getResult();
    }
}