<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use HealthCareAbroad\HelperBundle\Entity\Affiliation;

use Doctrine\ORM\EntityRepository;

/**
 * AffiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliationRepository extends EntityRepository
{

}