<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use HealthCareAbroad\HelperBundle\Entity\AwardingBody;

use Doctrine\ORM\EntityRepository;

/**
 * AwardingBodiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardingBodyRepository extends EntityRepository
{

}