<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	function getCityListByCountryId($countryId) {
		$criteria = array('status'=>1);
		$cities = $this->_em->getRepository('HelperBundle:City')->findBy($criteria);
		$arrCities = array();
		foreach($cities as $each){
			$arrCities[$each->getId()] = $each->getName();
		}
	
		return $arrCities;
	}
}