<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use HealthCareAbroad\HelperBundle\Entity\ContactDetail;

use Doctrine\ORM\EntityRepository;

/**
 * ContactDetail
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDetailRepository extends EntityRepository
{
    
}