<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use HealthCareAbroad\HelperBundle\Entity\FeedbackMessage;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackMessageRepository extends EntityRepository
{
    
}