<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HelperTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelperTextRepository extends EntityRepository
{
    public function findByRoute($route)
    {
        return $this->_em->createQueryBuilder()
        ->add('select', 'c')
        ->add('from', 'HelperBundle:HelperText c')
        ->add('where', 'c.route = :route')
        ->setParameter('route', $route);
    }
}