<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	function getNewsList() {
		$countries = $this->_em->getRepository('HelperBundle:News')->findByStatus(1);
		$arrNews = array();
		foreach($news as $each){
			$arrNews[$each->getId()] = $each->getTitle();
		}
	
		return $arrNews;
	}
	
	public function getQueryBuilderForNews()
	{
		return $this->_em->createQueryBuilder()
		->add('select', 'c')
		->add('from', 'HelperBundle:News c')
		->add('where', 'c.status = 1');
	}
}