<?php

namespace HealthCareAbroad\HelperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	function searchTags($term = '', $limit = 10)
	{
		$query = $this->_em->createQuery("SELECT Tag.id, Tag.name FROM HelperBundle:Tag AS Tag WHERE Tag.name LIKE '%$term%' AND Tag.status = 1 ORDER BY Tag.name ASC");
		$result = $query->setMaxResults($limit)->getArrayResult();
		$data = array();

		foreach($result as $tag) {
			$data[] = array(
				'id' => $tag['id'],
				'value' => $tag['name']
			);
		}

		return $data;
	}
	
}