<?php

namespace HealthCareAbroad\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use HealthCareAbroad\UserBundle\Entity\SiteUser;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserRepository extends EntityRepository
{
    public function findActiveUserById($accountId)
    {
        return $this->findOneBy(array('accountId' => $accountId, 'status' => SiteUser::STATUS_ACTIVE));
    }
}