<?php

namespace HealthCareAbroad\UserBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

use HealthCareAbroad\InstitutionBundle\Entity\Institution;

use HealthCareAbroad\UserBundle\Entity\SiteUser;

use Doctrine\ORM\EntityRepository;

use \Exception;

/**
 * InstitutionUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionUserRepository extends EntityRepository
{
    public function findActiveUserById($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a,b,c')
            ->from('UserBundle:InstitutionUser', 'a')
            ->innerJoin('a.institutionUserType', 'b')
            ->innerJoin('b.institutionUserRoles', 'c')
            ->where('a.accountId = :accountId')
            ->andWhere('a.status = :activeStatus')
                ->setParameter('accountId', $id)
            ->setParameter('activeStatus', SiteUser::STATUS_ACTIVE);
        
        return $qb->getQuery()->getOneOrNullResult();
        
        //return $this->findOneBy(array('accountId' => $id, 'status' => SiteUser::STATUS_ACTIVE));
    }
    
    public function findByInstitutionId(Institution $institution, $status=null)
    {
        if (!$institution->getId()) {
            throw new \Exception("Cannot find users of invalid institution.");
        }
        
        $criteria = array('institutionId' => $institutionId);
        if (!\is_null($status)) {
            $criteria['status'] = $status;
        }
        return $this->findBy($criteria); 
    }
    
    public function findByTypeName(Institution $institution, $userTypeName)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('u')
            ->from('UserBundle:InstitutionUser', 'u')
            ->join('u.institutionUserType', 't', Join::WITH, 't.name LIKE :userTypeName')
            ->where('u.institution = :institutionId')
            ->andWhere('u.status = :status')
            ->setParameter('userTypeName', '%'.$userTypeName.'%')
            ->setParameter('institutionId', $institution->getId())
            ->setParameter('status', SiteUser::STATUS_ACTIVE)
            ->getQuery();
        
        return $query->getResult();
    }
}