<?php

namespace HealthCareAbroad\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionUserRepository extends EntityRepository
{
}