<?php

namespace HealthCareAbroad\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionUserTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionUserTypeRepository extends EntityRepository
{
	/**
	 * Get all institution user types that are editable
	 */
	function getAllUserTypes() {
		$userTypes = $this->_em->getRepository('UserBundle:InstitutionUserTypes')->findByStatus(1);
		$arrUserTypes = array();
		foreach($userTypes as $each){
			$arrUserTypes[$each->getId()] = $each->getName();
		}
	
		return $arrUserTypes;
	}
	
	function getUserTypesByInstitutionId($institutionId) {
		$criteria = array('status'=>1);
		$userTypes = $this->_em->getRepository('UserBundle:InstitutionUserTypes')->findBy($criteria);
		$arrUserTypes = array();
		foreach($userTypes as $each){
			$arrUserTypes[$each->getId()] = $each->getName();
		}
	
		return $arrUserTypes;
	}
	
}