<?php

namespace HealthCareAbroad\UserBundle\Repository;

use HealthCareAbroad\InstitutionBundle\Entity\Institution;
use HealthCareAbroad\UserBundle\Entity\InstitutionUserRole;
use HealthCareAbroad\UserBundle\Entity\InstitutionUserType;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionUserRoleRepository extends EntityRepository
{
    /**
     * Get permissions that can be assigned to a user type
     */
    public function getAssignablePermissions()
    {
        $dql = "SELECT a FROM UserBundle:InstitutionUserRole a WHERE a.status = :active";
        $query = $this->getEntityManager()->createQuery($dql)
        ->setParameter('active', InstitutionUserRole::STATUS_ACTIVE);
        return $query->getResult();
    }

    public function getAssignablePermissionsByUserType(InstitutionUserType $userType)
    {
        $currentUserRoles = $userType->getInstitutionUserRoles();

        $ids = array();
        foreach ($currentUserRoles as $each) {
            $ids[] = $each->getId();
        }
        $idsNotIn = "'".\implode("', '",$ids)."'";

        $dql = "SELECT a FROM UserBundle:InstitutionUserRole a WHERE a.status = :active AND a.id NOT IN ({$idsNotIn})";
        $query = $this->getEntityManager()->createQuery($dql)
        ->setParameter('active', InstitutionUserRole::STATUS_ACTIVE);
        return $query->getResult();
    }

}