<?php

namespace HealthCareAbroad\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderUserRoleRepository2 extends EntityRepository
{
}