<?php

namespace HealthCareAbroad\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingPropertyChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingPropertyChoiceRepository extends EntityRepository
{
}