<?php

namespace HealthCareAbroad\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingRepository extends EntityRepository
{
	public function search($criteria = array()) {
		$query = $this->_em->createQuery($this->generateDqlForBasicSearch($criteria));

		return $query->getResult();
	}
	
	private function generateDqlForBasicSearch($criteria) {
		//TODO: provider id
		$dql = "SELECT l FROM ListingBundle:Listing l";
		$whereClause = " WHERE l.title LIKE '%".$criteria['searchTerm']."%' "; 
		
		if (isset($criteria['countryId']) && isset($criteria['cityId'])) {
			
			//$dql .= " LEFT JOIN l.listing_location ListingBundle:ListingLocation ll ON  ";			
			
		} else if (isset($criteria['countryId'])) {
			
		} else if (isset($criteria['cityId'])) {
			
		}

		$dql .= $whereClause;
		
		return $dql;
	}
}