<?php

namespace HealthCareAbroad\LogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ErrorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorLogRepository extends EntityRepository
{
}