<?php

namespace HealthCareAbroad\LogBundle\Repository;



/**
 * ErrorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Gedmo\Loggable\Entity\Repository\LogEntryRepository;

class VersionEntryRepository extends LogEntryRepository
{
}