<?php

namespace HealthCareAbroad\ProcedureBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalProcedureRepository extends EntityRepository
{
}