<?php

namespace HealthCareAbroad\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterSubscriberRepository extends EntityRepository
{
}