<?php

namespace HealthCareAbroad\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminUserTypeRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserTypeRoleRepository extends EntityRepository
{
}