<?php

namespace HealthCareAbroad\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
	public function getActiveLanguages($limit = null)
	{
		$qb = $this->createQueryBuilder('b')
		->select('b')
		->add('from', 'AdminBundle:Language b')
		->add('where', 'b.status = 1')
		->addOrderBy('b.name', 'ASC');
	
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
	
		return $qb->getQuery()
		->getResult();
	}
}