<?php

namespace HealthCareAbroad\AdminBundle\Repository;

use HealthCareAbroad\AdminBundle\Entity\Language;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
	public function getActiveLanguages($limit = null)
	{
		$qb = $this->createQueryBuilder('b')
		->select('b')
		->add('from', 'AdminBundle:Language b')
		->add('where', 'b.status = :status')
		->setParameter('status', Language::STATUS_ACTIVE)
		->addOrderBy('b.name', 'ASC');
	
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
	
		return $qb->getQuery()
		->getResult();
	}
	
	function getInstitutionLanguage($institutionId)
	{
		$conn = $this->_em->getConnection();
		$qry = "SELECT b.name,b.id FROM institution_languages_spoken AS a " .
						"JOIN languages AS b ON a.language_id = b.id " .
						"JOIN  institutions AS c ON a.institution_id = c.id " .
						"WHERE a.institution_id = $institutionId ";
		
		$result = $conn->executeQuery($qry)->fetchAll();

		return $result;
	}
}